# Makefile autogenerated by premake
# Don't edit this file! Instead edit `premake.lua` then rerun `make`
# Options:
#   CONFIG=[Release]

ifndef CONFIG
  CONFIG=Release
endif

export CONFIG

.PHONY: all clean engine

all: engine

Makefile: premake.lua
	@echo ==== Regenerating Makefiles ====
	@premake --file $^ --target gnu

engine:
	@echo ==== Building engine ====
	@$(MAKE) --no-print-directory -C . -f engine.make

clean:
	@$(MAKE) --no-print-directory -C . -f engine.make clean
